### ISSUE TITLE
MR6-bit stop deleting my issues

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [MR6-bit/-a1.o.16-MineCraft-AfterTime#5]
J39/MR6-bit stole this mod so i created an issue named "Stolen Mod" he deleted that issue meaning that his mod is actually stolen

**Comment by MR6-bit** [comment]
i deleted the issue bc you seek attention, even my old friends can prove that my mod isnt stolen, pls go to your parents for attention not me, like get out of my head

**Comment by GuestSneezeOSDev** [comment]
> i deleted the issue bc you seek attention, even my old friends can prove that my mod isnt stolen, pls go to your parents for attention not me, like get out of my head

bro stop lying this mod is stolen

**Comment by MR6-bit** [comment]
grow some balls, stop being a bitch about it, mod isnt stolen and everyone can prove it, imagine being a lil bitch to a small mod, you are just doing this bc you seek attention and that i quit hl2 sandbox modding, bc if i didnt quit hl2 sandbox modding. this wouldnt be you rambling lies like a lil bitch and again grow some balls

**Comment by GuestSneezeOSDev** [comment]
> grow some balls, stop being a bitch about it, mod isnt stolen and everyone can prove it, imagine being a lil bitch to a small mod, you are just doing this bc you seek attention and that i quit hl2 sandbox modding, bc if i didnt quit hl2 sandbox modding. this wouldnt be you rambling lies like a lil bitch and again grow some balls

shiver me fucking timbers 🥶

**Comment by MR6-bit** [comment]
show me what i stole

**Comment by GuestSneezeOSDev** [comment]
> show me what i stole

decompiled code reveals alot it shows you used chatgpt

**Comment by MR6-bit** [comment]
am gonna delete this issue, bc its solved

**Comment by GuestSneezeOSDev** [comment]
> ###
> [Dec 2, 2024](#issuecomment-2510300098)

you shouldnt do that

**Comment by MR6-bit** [comment]
why?

**Comment by GuestSneezeOSDev** [comment]
> why?

cause that would be unproffesional

**Comment by MR6-bit** [comment]
the fuck does that mean

**Comment by GuestSneezeOSDev** [comment]
bro is 12

**Comment by MR6-bit** [comment]
oh so am 12 bc you telling me deleting this issue is unprofessional? if thats a great logic then you are just a 10 year bc of the n word spams you made

**Comment by GuestSneezeOSDev** [comment]
> oh so am 12 bc you telling me deleting this issue is unprofessional? if thats a great logic then you are just a 10 year bc of the n word spams you made

how am I 10? you literally spammed the nword in every server i was in

**Comment by MR6-bit** [comment]
![image](https://github.com/user-attachments/assets/c0289ae6-8161-4c38-9985-8b0ec9696340)

**Comment by MR6-bit** [comment]
![image](https://github.com/user-attachments/assets/cc925eef-e3f6-4d06-a433-3e37ebd4b756)

**Comment by MR6-bit** [comment]
![image](https://github.com/user-attachments/assets/fbddae2d-8b37-40c0-96e7-d84e74eb356e)

**Comment by MR6-bit** [comment]
should i add more?

**Comment by MR6-bit** [comment]
to clarify, its been 11 days since you started this drama and you just ttying to keep it longer like bro move on

**Comment by GuestSneezeOSDev** [comment]
do i smell fake font?

**Comment by MR6-bit** [comment]
do i smell 0 intelligence?

**Comment by MR6-bit** [comment]
![image](https://github.com/user-attachments/assets/18c9d411-b88a-4500-9edd-3b823d6a0716)

**Comment by MR6-bit** [comment]
![image](https://github.com/user-attachments/assets/41a00b35-3b09-4dad-958a-a1cf8215d3d7)

**Comment by MR6-bit** [comment]
should i add more or will you stop fucking continuing this drama, move on bro

**Comment by MR6-bit** [comment]
calling me a black mailer for showing the truth doesnt make you any better, it just makes you a walking punchline

**Comment by GuestSneezeOSDev** [comment]
> calling me a black mailer for showing the truth doesnt make you any better, it just makes you a walking punchline

wdym?
